export { default as cart } from './cart.svg'
export { default as couple } from './couple.png'
export { default as logo } from './logo.png'
export { default as pix } from './pix.png'
export { default as shower } from './shower.png'
export { default as showerMobile } from './shower_mobile.png'
export { default as smile } from './smile.svg'
